/*
Copyright Abu Saleh.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	salehdevv1alpha1 "github.com/Saleh7127/sample-controller/pkg/apis/saleh.dev/v1alpha1"
	versioned "github.com/Saleh7127/sample-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Saleh7127/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/Saleh7127/sample-controller/pkg/client/listers/saleh.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UbanInformer provides access to a shared informer and lister for
// Ubans.
type UbanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.UbanLister
}

type ubanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewUbanInformer constructs a new informer for Uban type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUbanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUbanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredUbanInformer constructs a new informer for Uban type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUbanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SalehV1alpha1().Ubans(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SalehV1alpha1().Ubans(namespace).Watch(context.TODO(), options)
			},
		},
		&salehdevv1alpha1.Uban{},
		resyncPeriod,
		indexers,
	)
}

func (f *ubanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUbanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ubanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&salehdevv1alpha1.Uban{}, f.defaultInformer)
}

func (f *ubanInformer) Lister() v1alpha1.UbanLister {
	return v1alpha1.NewUbanLister(f.Informer().GetIndexer())
}
