/*
Copyright Abu Saleh.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/Saleh7127/sample-controller/pkg/apis/saleh.dev/v1alpha1"
	salehdevv1alpha1 "github.com/Saleh7127/sample-controller/pkg/client/applyconfiguration/saleh.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUbans implements UbanInterface
type FakeUbans struct {
	Fake *FakeSalehV1alpha1
	ns   string
}

var ubansResource = v1alpha1.SchemeGroupVersion.WithResource("ubans")

var ubansKind = v1alpha1.SchemeGroupVersion.WithKind("Uban")

// Get takes name of the uban, and returns the corresponding uban object, and an error if there is any.
func (c *FakeUbans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Uban, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ubansResource, c.ns, name), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}

// List takes label and field selectors, and returns the list of Ubans that match those selectors.
func (c *FakeUbans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UbanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ubansResource, ubansKind, c.ns, opts), &v1alpha1.UbanList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UbanList{ListMeta: obj.(*v1alpha1.UbanList).ListMeta}
	for _, item := range obj.(*v1alpha1.UbanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ubans.
func (c *FakeUbans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ubansResource, c.ns, opts))

}

// Create takes the representation of a uban and creates it.  Returns the server's representation of the uban, and an error, if there is any.
func (c *FakeUbans) Create(ctx context.Context, uban *v1alpha1.Uban, opts v1.CreateOptions) (result *v1alpha1.Uban, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ubansResource, c.ns, uban), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}

// Update takes the representation of a uban and updates it. Returns the server's representation of the uban, and an error, if there is any.
func (c *FakeUbans) Update(ctx context.Context, uban *v1alpha1.Uban, opts v1.UpdateOptions) (result *v1alpha1.Uban, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ubansResource, c.ns, uban), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUbans) UpdateStatus(ctx context.Context, uban *v1alpha1.Uban, opts v1.UpdateOptions) (*v1alpha1.Uban, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ubansResource, "status", c.ns, uban), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}

// Delete takes name of the uban and deletes it. Returns an error if one occurs.
func (c *FakeUbans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ubansResource, c.ns, name, opts), &v1alpha1.Uban{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUbans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ubansResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UbanList{})
	return err
}

// Patch applies the patch and returns the patched uban.
func (c *FakeUbans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Uban, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ubansResource, c.ns, name, pt, data, subresources...), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied uban.
func (c *FakeUbans) Apply(ctx context.Context, uban *salehdevv1alpha1.UbanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Uban, err error) {
	if uban == nil {
		return nil, fmt.Errorf("uban provided to Apply must not be nil")
	}
	data, err := json.Marshal(uban)
	if err != nil {
		return nil, err
	}
	name := uban.Name
	if name == nil {
		return nil, fmt.Errorf("uban.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ubansResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeUbans) ApplyStatus(ctx context.Context, uban *salehdevv1alpha1.UbanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Uban, err error) {
	if uban == nil {
		return nil, fmt.Errorf("uban provided to Apply must not be nil")
	}
	data, err := json.Marshal(uban)
	if err != nil {
		return nil, err
	}
	name := uban.Name
	if name == nil {
		return nil, fmt.Errorf("uban.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ubansResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Uban{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Uban), err
}
