/*
Copyright Abu Saleh.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/Saleh7127/sample-controller/pkg/apis/saleh.dev/v1alpha1"
	salehdevv1alpha1 "github.com/Saleh7127/sample-controller/pkg/client/applyconfiguration/saleh.dev/v1alpha1"
	scheme "github.com/Saleh7127/sample-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UbansGetter has a method to return a UbanInterface.
// A group's client should implement this interface.
type UbansGetter interface {
	Ubans(namespace string) UbanInterface
}

// UbanInterface has methods to work with Uban resources.
type UbanInterface interface {
	Create(ctx context.Context, uban *v1alpha1.Uban, opts v1.CreateOptions) (*v1alpha1.Uban, error)
	Update(ctx context.Context, uban *v1alpha1.Uban, opts v1.UpdateOptions) (*v1alpha1.Uban, error)
	UpdateStatus(ctx context.Context, uban *v1alpha1.Uban, opts v1.UpdateOptions) (*v1alpha1.Uban, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Uban, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UbanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Uban, err error)
	Apply(ctx context.Context, uban *salehdevv1alpha1.UbanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Uban, err error)
	ApplyStatus(ctx context.Context, uban *salehdevv1alpha1.UbanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Uban, err error)
	UbanExpansion
}

// ubans implements UbanInterface
type ubans struct {
	client rest.Interface
	ns     string
}

// newUbans returns a Ubans
func newUbans(c *SalehV1alpha1Client, namespace string) *ubans {
	return &ubans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the uban, and returns the corresponding uban object, and an error if there is any.
func (c *ubans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Uban, err error) {
	result = &v1alpha1.Uban{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ubans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Ubans that match those selectors.
func (c *ubans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UbanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UbanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ubans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ubans.
func (c *ubans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ubans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a uban and creates it.  Returns the server's representation of the uban, and an error, if there is any.
func (c *ubans) Create(ctx context.Context, uban *v1alpha1.Uban, opts v1.CreateOptions) (result *v1alpha1.Uban, err error) {
	result = &v1alpha1.Uban{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ubans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(uban).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a uban and updates it. Returns the server's representation of the uban, and an error, if there is any.
func (c *ubans) Update(ctx context.Context, uban *v1alpha1.Uban, opts v1.UpdateOptions) (result *v1alpha1.Uban, err error) {
	result = &v1alpha1.Uban{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ubans").
		Name(uban.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(uban).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *ubans) UpdateStatus(ctx context.Context, uban *v1alpha1.Uban, opts v1.UpdateOptions) (result *v1alpha1.Uban, err error) {
	result = &v1alpha1.Uban{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ubans").
		Name(uban.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(uban).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the uban and deletes it. Returns an error if one occurs.
func (c *ubans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ubans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ubans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ubans").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched uban.
func (c *ubans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Uban, err error) {
	result = &v1alpha1.Uban{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ubans").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied uban.
func (c *ubans) Apply(ctx context.Context, uban *salehdevv1alpha1.UbanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Uban, err error) {
	if uban == nil {
		return nil, fmt.Errorf("uban provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(uban)
	if err != nil {
		return nil, err
	}
	name := uban.Name
	if name == nil {
		return nil, fmt.Errorf("uban.Name must be provided to Apply")
	}
	result = &v1alpha1.Uban{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("ubans").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *ubans) ApplyStatus(ctx context.Context, uban *salehdevv1alpha1.UbanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Uban, err error) {
	if uban == nil {
		return nil, fmt.Errorf("uban provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(uban)
	if err != nil {
		return nil, err
	}

	name := uban.Name
	if name == nil {
		return nil, fmt.Errorf("uban.Name must be provided to Apply")
	}

	result = &v1alpha1.Uban{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("ubans").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
